### ISSUE TITLE
Email notification fails

### ISSUE THREAD

**Issue by ctueck** [EQAR/eqar_backend#334]
There seem to be some cases where no submission email confirmation is sent. We had one example today, report no. 52759, and here's what I could find in the logs:

```
[2020-07-16 10:11:08,646: INFO/MainProcess] Received task: send_submission_email[c6d3bd44-90fb-4bcb-b9a5-80b2bd97d685]
[2020-07-16 10:11:08,666: INFO/ForkPoolWorker-2] Finished 'http://localhost:8983/solr/deqar-reports/update/?commit=true' (post) with body '<add><doc>' in 0.045 seco
nds, with status 200
[2020-07-16 10:11:08,666: WARNING/ForkPoolWorker-2] Indexing Report No. 52759!
[2020-07-16 10:11:08,667: INFO/ForkPoolWorker-2] Task index_report[b09e1e48-c60e-4221-97fe-3624a8fe555e] succeeded in 0.12432477250695229s: None
[2020-07-16 10:11:09,078: INFO/ForkPoolWorker-2] Finished 'http://localhost:8983/solr/deqar-institutions/update/?commit=true' (post) with body '<add><doc>' in 0.033
 seconds, with status 200
[2020-07-16 10:11:09,079: WARNING/ForkPoolWorker-2] Indexed Institution No. 840!
[2020-07-16 10:11:09,080: INFO/ForkPoolWorker-2] Task index_institution[8600c5d1-7e7a-4f4c-98ef-35307f8e4fca] succeeded in 0.40735007729381323s: None
[2020-07-16 10:11:09,195: INFO/ForkPoolWorker-2] Finished 'http://localhost:8983/solr/deqar-reports/update/?commit=true' (post) with body '<add><doc>' in 0.050 seco
nds, with status 200
[2020-07-16 10:11:09,195: WARNING/ForkPoolWorker-2] Indexing Report No. 52759!
[2020-07-16 10:11:09,196: INFO/ForkPoolWorker-2] Task index_report[5608a509-543b-4ddf-87f2-37eba7f6e9b3] succeeded in 0.11272619944065809s: None
[2020-07-16 10:11:09,586: INFO/ForkPoolWorker-2] Finished 'http://localhost:8983/solr/deqar-institutions/update/?commit=true' (post) with body '<add><doc>' in 0.025
 seconds, with status 200
[2020-07-16 10:11:09,587: WARNING/ForkPoolWorker-2] Indexed Institution No. 840!
[2020-07-16 10:11:09,588: INFO/ForkPoolWorker-2] Task index_institution[34e096e4-4744-47aa-9222-eccda9804437] succeeded in 0.3879423728212714s: None
[2020-07-16 10:11:09,709: INFO/ForkPoolWorker-2] Finished 'http://localhost:8983/solr/deqar-reports/update/?commit=true' (post) with body '<add><doc>' in 0.027 seco
nds, with status 200
[2020-07-16 10:11:09,709: WARNING/ForkPoolWorker-2] Indexing Report No. 52759!
[2020-07-16 10:11:09,710: INFO/ForkPoolWorker-2] Task index_report[2e250c9c-27a8-4f9c-a46d-42bedcc991d5] succeeded in 0.11855597142130136s: None
[2020-07-16 10:11:10,203: INFO/ForkPoolWorker-2] Finished 'http://localhost:8983/solr/deqar-institutions/update/?commit=true' (post) with body '<add><doc>' in 0.081
 seconds, with status 200
[2020-07-16 10:11:10,204: WARNING/ForkPoolWorker-2] Indexed Institution No. 840!
[2020-07-16 10:11:10,204: INFO/ForkPoolWorker-2] Task index_institution[7ee1dede-cd4b-437a-924b-527d65c47c72] succeeded in 0.4905068939551711s: None
[2020-07-16 10:11:10,222: ERROR/ForkPoolWorker-2] Task send_submission_email[c6d3bd44-90fb-4bcb-b9a5-80b2bd97d685] raised unexpected: KeyError('institutions',)
Traceback (most recent call last):
  File "/opt/deqar_backend/python3/lib/python3.5/site-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/deqar_backend/python3/lib/python3.5/site-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/deqar_backend/eqar_backend/submissionapi/tasks.py", line 31, in send_submission_email
    for inst in resp['submitted_report']['institutions']:
KeyError: 'institutions'
```

**Comment by JoshBone** [comment]
I think that this could be the case, that what we discovered, that a package without an institution key passed the validation.
