### ISSUE TITLE
Synchronise institution data from OrgReg and ETER

### ISSUE THREAD

**Issue by ctueck** [EQAR/eqar_backend#444]
As discussed, here are some points for the OrgReg/ETER synchronisation based on the semi-automatic workflow used so far:

## General

OrgReg API documentation is at <https://register.orgreg.joanneum.at/api/doc/>, the endpoint for the full set of data on one higher education institution (HEI) is `/api/2.0/entity-details/{entityId}`.

OrgReg provides a simple list of all known IDs at `/api/2.0/organizations/entity-ids`, but one issue here is that this includes *all* types of organisations and it seems it cannot be filtered. `/api/2.0/organizations/query` needs authentication and should allow querying only HEIs (numerical type 1, see also `/api/2.0/organizations/filters` - but I am not sure our existing token still works or whether the authentication system was changed meanwhile.

Data imported from OrgReg before is marked in source note or similar fields formatted `OrgReg-[year of import]-[corresponding OrgReg ID] [OrgReg comment/note]`, e.g. `OrgReg-2020-DEMOFR001 ...`.

OrgReg uses a `a` as a special code to denote "not applicable" data (e.g. closing year of an HEI that is not closed) and `m` as a special code to denote missing or unknown data (e.g. closing year of an HEI that is closed but the information is missing when exactly it closed).

Demographic events and linkages in OrgReg might relate to entities that are in OrgReg, but out of scope for DEQAR (i.e. other organisations than HEIs). These should be ignored.

Data cleaning/adjustments that might be necessary:

- the last name's/characteristic's and location's end year are not always null/empty in OrgReg, but the closing year may be used as end date
- there might be previous names with an end year of `m` (= unknown), I defaulted that to something
- there could be closed institutions with an unknown closure year (i.e. `m`)
- when the official name is in English, OrgReg usually has that name identically in both fields - we'd have it as official name, with English name empty
- OrgReg uses `UK` as country code (EU-specific variattion) instead of `GB` (ISO)

## Entities ≘ Institutions

OrgReg has founding/closing years only, no dates. Founding year should be treated as `-01-01` and closing year as `-12-31`.

Identifiers to import/update and our corresponding resource string:

- National identifier (`NATID`) - `[country code]-ETER.BAS.NATID`
- Erasmus+ code (`ERASMUSCODE2127`) - `Erasmus`
- IAU World HE Database (`WHEDID`) - `WHED`

OrgReg also has the DEQARINST ID recorded. It would make sense to check for consistency and output a warning if there's a mismatch.

If we have an Erasmus code already but the field in OrgReg is empty, it's probably save to keep the one we have for historic reasons. If the Erasmus code in OrgReg differs this should be logged.

WHED codes aren't in DEQAR so far.

## Characteristics ≘ Names

The name start year should be converted to a day with `-07-01`, the end year with `-06-30`.

## Locations ≘ Institution Country

OrgReg's "legal seat" flag maps to the official flag (`country_verified`) on our side.

The start/end years should be converted to days with `-01-01` or `-12-31`, respectively.

## Demographic Events ≘ Historical Relationships

The types map as follows:

```
 OrgReg         ->  DEQAR
---------------    ----------------------------------
 5 (merger)         2 (succeeded / succeeded by)
 6 (split)          2
 7 (take-over)      3 (was absorbed by / absorbed)
 8 (spin-out)       4 (was spun off from / spun off)
```

Parent (OrgReg) is normally Source (DEQAR), except for type 7: Parent (OrgReg) = Target (DEQAR)

Likewise, Child (OrgReg) is normally Target (DEQAR),except for type 7: Child (OrgReg) = Source (DEQAR)

## Linkages ≘ Hierarchical Relationships

The types map as follows:

```
 OrgReg           ->  DEQAR
-----------------    ----------------------------------
 1 (membership)       1 ("consortium")
 2 (affiliated)       1 ("consortium")
 3 (association)      (not imported)
 4 (joint unit)       (not imported)
```

(OrgReg types 3/4 are only loosely related, hence we don't record those; faculties are not present in OrgReg, hence we don't find that relationship type.)

Entity 1 (OrgReg) becomes Child (DEQAR) and Entity 2 (OrgReg) becomes Parent (DEQAR).

## From ETER: QF-EHEA levels

API documentation at <https://www.eter-project.com/api/doc/>

Generally, the QF EHEA levels for one institution could be retrieved by a (POST) request to <https://www.eter-project.com/api/3.0/HEIs/query>:

```json
{
  "filter": {
    "BAS.ETERID.v": "{ETER ID}"
  },
  "fieldIds": {
    "BAS.REFYEAR": 1,
    "STUD.LOWDEG": 1,
    "STUD.HIGHDEG": 1
  },
  "searchTerms": []
}
```

(But the API isn't responding right now, so cannot test if that query still works and needs auth or not.)

**Comment by ctueck** [comment]
So, after some more testing, here are a number of open issues:

### Hierarchical relationships

Some cases lead to this exception:

```
Processing institution BE0076 (70 of 205)Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/deqar/institutions/management/commands/orgreg_sync.py", line 36, in handle
    orgreg_sync.run()
  File "/deqar/institutions/orgreg/orgreg_synchronizer.py", line 105, in run
    self.sync_hierarchical_relationships()
  File "/deqar/institutions/orgreg/orgreg_synchronizer.py", line 604, in sync_hierarchical_relationships
    self.report.add_report_line('  Date From: %s' % values_to_update['date_from']['log'])
KeyError: 'date_from'
```

It might be a simple typo in the dict key.

### HEIs newly appearing in OrgReg

Needs to be implemented still.

### New locations

Seem to lead to this exception:

```
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/deqar/institutions/management/commands/orgreg_sync.py", line 36, in handle
    orgreg_sync.run()
  File "/deqar/institutions/orgreg/orgreg_synchronizer.py", line 102, in run
    self.sync_locations()
  File "/deqar/institutions/orgreg/orgreg_synchronizer.py", line 378, in sync_locations
    InstitutionCountry.objects.create(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 422, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 743, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 780, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 873, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 910, in _do_insert
    return manager._insert([self], fields=fields, return_id=update_pk,
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1376, in execute_sql
    for sql, params in self.as_sql():
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1318, in as_sql
    value_rows = [
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1319, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1319, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1260, in prepare_value
    value = field.get_db_prep_save(value, connection=self.connection)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 793, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 1279, in get_db_prep_value
    value = self.get_prep_value(value)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 1274, in get_prep_value
    return self.to_python(value)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 1236, in to_python
    parsed = parse_date(value)
  File "/usr/local/lib/python3.8/site-packages/django/utils/dateparse.py", line 74, in parse_date
    match = date_re.match(value)
TypeError: expected string or bytes-like object
```

### Default dates

In general:

- We should only apply defaults for fields required in our models.
- If we have a date recorded already and it's now unknown by OrgReg (`m` code) I think we should keep what we have and not overwrite by default. Or in other words: default dates should basically be used for newly discovered records only, but not for updating existing ones - they should only be updated with "real" dates.

For the different fields:

- Location start date: use institution founding date if known, and current year only if no founding date. We'll mainly have new locations that have existed for long and are only more recently recorded in OrgReg, rather than actually new locations. (And above all, I don't know if we actually use location dates for anything.)

- Name end date: current year for newly discovered former names with unknown end - this might be a rare case, if at all.

- Hierarchical relationship: no default needed as start/end dates not required

- Historical relationship: current year

### Update base data

A bug in https://github.com/EQAR/eqar_backend/blob/development/institutions/orgreg/orgreg_synchronizer.py#L712 yields the following exception:

```
Processing institution AT0001 (1 of 1)Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/deqar/institutions/management/commands/orgreg_sync.py", line 36, in handle
    orgreg_sync.run()
  File "/deqar/institutions/orgreg/orgreg_synchronizer.py", line 101, in run
    self.sync_base_data()
  File "/deqar/institutions/orgreg/orgreg_synchronizer.py", line 123, in sync_base_data
    self._update_base_data('founding_date', compare)
  File "/deqar/institutions/orgreg/orgreg_synchronizer.py", line 712, in _update_base_data
    self.inst[field] = compare_data['orgreg_value']
TypeError: 'Institution' object does not support item assignment
```

### Relationships to/with unknown institutions

A (historical or hierarchical) relationship with an OrgReg ID unknown in DEQAR should be a warning (at most), not an error: it usually means that the other entity is not a HEI and hence not in our scope.

### Drop ETER shadow table

Can we drop the ETER "shadow table" and keep the OrgReg/ETER ID in a unique string field directly in the institution model?

### Handling OrgReg API errors

It would be useful to handle OrgReg API errors. In the last days, their system was down a few times (with a HTTP 503 status), which currently leads to the message "OrgReg record(s) can not be found with the defined criteria." - maybe there should be a distinction between an empty result set vs. an API error.

### Error handling

When an exception occurs, the whole sync script aborts and the log is never printed - even though some operations might have succeeded and even been committed/saved before.

As there's always some potential for exceptions we haven't seen/thought of, we should make sure that at least the log so far is printed - or maybe even make sure that sync continues with the next institution if we see any other uncaught exceptions during handling one case?

### Sub-countries

Issue #450 has some impact in terms of resolving OrgReg country codes to DEQAR country records - could be implemented immediately or once everything else is solved, but it is a high priority issue.

**Comment by ctueck** [comment]
From the first few runs in production, a few smaller issues came up:

- The latitude/longitude comparison should maybe be non-exact with some limit of significant digits. I think it's a typical floating point issue, sometimes the value gets updated for a "change" in the 9th digit behind the comma or so...
- We get a lot of "ERROR - Matching RelationshipType can't be found ..." for types we deliberately ignore. I'd suggest to map types 3 and 4 to `None` in https://github.com/EQAR/eqar_backend/blob/master/institutions/orgreg/orgreg_synchronizer.py#L703-L706 and then in https://github.com/EQAR/eqar_backend/blob/master/institutions/orgreg/orgreg_synchronizer.py#L762-L764 to silently ignore and pass if it's `None` - so we only see an error if it's really unknown.
- We can generally ignore the "WARNING - Child Institution doesn't exist with OrgReg ID ..." - either it's a non-HEI or it's a new HEI, in which case it would be processed in the next run at the latest. Possibly we could have a switch to enable them if needed, but in normal use they just flood the log.

### Name records issue
There are a few scenarios where the HEI has a new name, the old name gets a default expiry date in run N, but then gets updated to it's real exptry date in run N+1. Example:

Run N:
```
----------------------------------------------------------------------------------------------------
Institution record AL0028 / DEQARINST5887 (UPDATE)
University College Luarasi
----------------------------------------------------------------------------------------------------
**ADD - WHED: IAU-019909
**ADD - LOCATION
  Country: Albania
  City: Tirana
  Latitude: 41.31916
  Longitude: 19.82858
  Official: YES
  Valid From: 2023-01-01
  Valid To: None
  Source Note: OrgReg-2023-LOCATAL0028-1
**ADD - NAME RECORD
  Name English: Luarasi University
  Name Official: Universiteti Luarasi
  Acronym: UL
  Valid To: None
  Source Note: OrgReg-2023-CHARAL0028-2
**UPDATE - NAME RECORD
**Because of a new name record as added without valid_to date.
  Name English: University College Luarasi
  Valid To: 2023-02-04 13:04:09.078240
```

Run N+1:
```
----------------------------------------------------------------------------------------------------
Institution record AL0028 / DEQARINST5887 (UPDATE)
Luarasi University
----------------------------------------------------------------------------------------------------
**UPDATE - NAME RECORD
  Name English: University College Luarasi
  Name Official: Kolegji Universitar "Luarasi"
  Acronym:
  Valid To: 2023-02-04 <- 2019-12-31
  Source Note: OrgReg-2023-CHARAL0028-1
```

I don't know why the name record with OrgReg-2023-CHARAL0028-1 isn't already updated to its correct date in run N?

### Timeout issue
Finally, there should also be a (generous) timeout for OrgReg API requests. The retry logic works very well, but we had one case where the API was down without a HTTP error code but just a connection request timing out. Because the requests library has no timeout by default, it takes ~50min until the script fails in this case.

**Comment by ctueck** [comment]
>  The latitude/longitude comparison should maybe be non-exact with some limit of significant digits. I think it's a typical floating point issue, sometimes the value gets updated for a "change" in the 9th digit behind the comma or so...

For illustration, this is a recent example of that issue:
```
----------------------------------------------------------------------------------------------------
Institution record FR0292 / DEQARINST1173 (UPDATE)
INSPé de l'académie de Dijon
----------------------------------------------------------------------------------------------------
**UPDATE - LOCATION
  Country: France
  City: Nevers
  Latitude: 47.004332
  Longitude: 3.155362 <- 3.1553620000000002
  Official: NO
  Valid From: 2023-01-01
  Valid To: None
  Source Note: OrgReg-2023-LOCATFR0292-4 identificatif de la commune:21231
```
