### ISSUE TITLE
OrgReg sync - possibly typo in log message

### ISSUE THREAD

**Issue by ctueck** [EQAR/eqar_backend#484]
One of the latest OrgReg syncs yielded this exception:

```
----------------------------------------------------------------------------------------------------
Institution record DE0837 / DEQARINST6950 (UPDATE)
EDU.CON Hochschule Berlin
----------------------------------------------------------------------------------------------------
**DELETE - NAME RECORD - [ID:9861, ]

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/deqar/institutions/management/commands/orgreg_sync.py", line 36, in handle
    orgreg_sync.run()
  File "/deqar/institutions/orgreg/orgreg_synchronizer.py", line 132, in run
    self.sync_locations()
  File "/deqar/institutions/orgreg/orgreg_synchronizer.py", line 488, in sync_locations
    self.report.add_report_line('**DELETE - LOCATION - [ID:%s, %s]' % (ic.id, ic.country_code))
AttributeError: 'InstitutionCountry' object has no attribute 'country_code'
1
```

Seems to be simply a typo in the variable name maybe?

**Comment by JoshBone** [comment]
Fixed by https://github.com/EQAR/eqar_backend/pull/487
